outsource/masterdata/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^polist/', views.po_list, name='polist'),
	url(r'^all-invoices/', views.all_invoices, name='all_invoices'),
	url(r'^yearly-report/', views.yearly_report, name='yearly_report'),
	url(r'^detail/(?P<pk>\d+)$', views.po_detail, name='detail'),
	url(r'^barcode/(?P<pk>\d+)$', views.barcode, name='barcode'),
	url(r'^invoice/(?P<pk>\d+)$', views.create_invoice, name='invoice'),
	url(r'^display-invoice/(?P<pk>\d+)$', views.display_invoice, name='display_invoice'),
	url(r'^$', views.index, name='index'),
]

outsource/outsource/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^masterdata/', include('masterdata.urls', namespace='masterdata')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

outsource/masterdata/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


PO_STATUS = (
	('open', 'PO Open'),
	('completed', 'PO Closed'),
)


class third_party_data(models.Model):
	since = models.DateTimeField(auto_now_add=True)
	name = models.CharField(max_length=150, unique=True)
	name_id = models.CharField(
		max_length=200, 
		unique=True, 
		help_text='All lowercase and no space'
	)
	contact_person = models.CharField(max_length=100)
	address = models.TextField()
	phone = models.CharField(max_length=50)
	email = models.EmailField(max_length=150, unique=True)
	is_active = models.BooleanField(default=True, help_text='Check if active')

	class Meta:
		abstract = True

	def __str__(self):
		return self.name


class Supplier(third_party_data):
	pass


class Customer(third_party_data):
	brand_name = models.CharField(
		max_length=150, 
		blank=True, 
		help_text='If no brand, could be empty'
	)


class Product(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	no = models.CharField(
		max_length=100, 
		help_text='Unique master code for all sizes and colors, example: MSN001'
	)
	code = models.CharField(
		max_length=100, 
		unique=True, 
		help_text='Unique product code with size and color codes, example: MSN001_BLK_XL'
	)
	name = models.CharField(max_length=200, help_text='Product name')
	description = models.TextField()
	size = models.CharField(max_length=20)
	color = models.CharField(max_length=20)
	category = models.CharField(max_length=100)
	collection = models.CharField(max_length=150, blank=True)
	supplier = models.ForeignKey(Supplier, to_field='name_id')
	brand_name = models.CharField(max_length=150, blank=True)
	prod_price = models.IntegerField(default=0, help_text='Production price')
	pub_price = models.IntegerField(default=0)
	retail_price = models.IntegerField(default=0)
	is_active = models.BooleanField(default=True, help_text='Check if active')
	edited_at = models.DateTimeField(auto_now=True)
	image = models.ImageField(default='images/noimage.jpg', upload_to='images')

	class Meta:
		verbose_name = 'Master Product'
		ordering = ['code']

	def __str__(self):
		return "{} | {} - {} | {}".format(self.code, self.color, self.size, self.name)


class PoOrder(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	customer = models.ForeignKey(Customer)
	po_supplier = models.CharField(max_length=50, unique=True)
	po_customer = models.CharField(max_length=50, unique=True)
	ready_date = models.DateTimeField()
	shipment_date = models.DateTimeField()
	status = models.CharField(
		max_length=10,
		choices=PO_STATUS,
		default='open'
	)
	edited_at = models.DateTimeField(auto_now=True)

	class Meta:
		verbose_name = 'PO Order'

	def __str__(self):
		return self.po_customer


class ProductPo(models.Model):
	po_order = models.ForeignKey(PoOrder)
	code = models.ForeignKey(Product)
	qty_order = models.IntegerField(blank=False)
	qty_ready = models.IntegerField(default=0)
	qty_invoice = models.IntegerField(default=0)
	qty_shipped = models.IntegerField(default=0)

	class Meta:
		verbose_name = 'Product PO'

	def __str__(self):
		return "{} | {} | {} pcs".format(
			self.po_order, self.code, self.qty_order)


class Invoice(models.Model):
	created_at = models.DateTimeField(auto_now_add=True)
	invoice_no = models.IntegerField(default=0)
	po_customer = models.ForeignKey(PoOrder)
	code = models.ForeignKey(Product)
	send_to_be_shipped = models.IntegerField(default=0)

	

outsource/masterdata/forms.py
from django import forms

from . import models


YEARS_CHOICES = [
	('2019', '2019'),
	('2020', '2020'),
	('2021', '2021'),
	('2022', '2022'),
	('2023', '2023'),
	('2024', '2025'),
]


class CheckForm(forms.Form):
	po_customer = forms.CharField(
		label='PO Numbers',
		max_length=20,
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Enter Your PO Numbers here',
			}
		),
	)


class YearsForm(forms.Form):
	year = forms.CharField(
		label='Select Years', 
		widget=forms.Select(
			choices=YEARS_CHOICES,
			attrs={
				'class': 'form-control',
			}
		),
	)

outsource/masterdata/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .forms import CheckForm, YearsForm
from .models import PoOrder, ProductPo, Invoice, Product

import random
import barcode


def index(request):
	check_form = CheckForm()

	context = {
		'page_title': 'PO Status',
		'check_form': check_form,
	}

	if request.method == 'POST':
		check_form = CheckForm(request.POST)

		if check_form.is_valid():
			context['po_customer'] = request.POST['po_customer']
			po_customer = context['po_customer']

			status = get_object_or_404(PoOrder, po_customer=po_customer)

			context['po_status'] = status.status
			context['po_id'] = status.id
			context['po_name'] = status.customer.name
			context['po_supplier'] = status.po_supplier
			context['po_ready'] = status.ready_date
			context['po_shipment'] = status.shipment_date

			return render(request, 'masterdata/po_status.html', context)

		else:
			check_form = CheckForm()

	return render(request, 'masterdata/index.html', context)


@login_required
def select_years(request):
	pass


def barcode(request, pk):
    import mybarcode

    barcode = ''
    retail_price = 0
    desc = ''
    size = ''
    color = ''
    po_product = ProductPo.objects.filter(code=pk)
    for product in po_product:
		barcode = product.code.code
		retail_price = product.code.retail_price
		desc = product.code.description
		size = product.code.size
		color = product.code.color

    d = mybarcode.MyBarcodeDrawing(barcode).save(formats=['png'],outDir='./media/barcodes/',fnRoot=barcode)
    # return HttpResponseRedirect('/media/barcodes/{}.pdf'.format(barcode))

    context = {
    	'barcode': barcode,
    	'retail_price': retail_price,
	    'desc': desc,
	    'size': size,
	    'color': color,
    }

    return render(request, 'masterdata/print_barcode.html', context)


@login_required
def po_list(request):
	po_list = PoOrder.objects.all().order_by('-id')

	context = {
		'page_title': 'PO List',
		'po_list': po_list,
	}
	return render(request, 'masterdata/po_list.html', context)


def po_detail(request, pk):
	po_products = ProductPo.objects.filter(po_order=pk)

	total_qty_order = 0
	total_qty_ready = 0
	total_qty_invoice = 0
	total_qty_shipped = 0
	total_amount_order = 0
	total_amount_ready = 0
	total_amount_invoice = 0
	total_amount_shipped = 0
	total_amount_profit = 0
	po_numbers = ''
	po_customer = ''
	ready_date = ''
	shipment_date = ''
	po_supplier = ''
	po_status = ''
	for product in po_products:
		total_qty_order += product.qty_order
		total_qty_ready += product.qty_ready
		total_qty_invoice += product.qty_invoice
		total_qty_shipped += product.qty_shipped
		po_numbers = product.po_order.po_customer
		po_customer = product.po_order.customer.name
		ready_date = product.po_order.ready_date
		shipment_date = product.po_order.shipment_date
		po_supplier = product.po_order.po_supplier
		po_status = product.po_order.status
		total_amount_order += (product.code.pub_price * product.qty_order)
		total_amount_ready += (product.code.pub_price * product.qty_ready)
		total_amount_invoice += (product.code.pub_price * product.qty_invoice)
		total_amount_shipped += (product.code.pub_price * product.qty_shipped)
		total_amount_profit += (product.code.prod_price * product.qty_shipped)

	context = {
		'page_title': 'PO Detail',
		'po_products': po_products,
		'total_qty_order': total_qty_order,
		'total_qty_ready': total_qty_ready,
		'total_qty_invoice': total_qty_invoice,
		'total_qty_shipped': total_qty_shipped,
		'total_amount_profit': total_amount_profit,
		'prod_id': pk,
		'po_numbers': po_numbers,
		'po_customer': po_customer,
		'ready_date': ready_date,
		'shipment_date': shipment_date,
		'po_supplier': po_supplier,
		'po_status': po_status,
		'total_amount_order': total_amount_order,
		'total_amount_ready': total_amount_ready,
		'total_amount_invoice': total_amount_invoice,
		'total_amount_shipped': total_amount_shipped,

	}
	return render(request, 'masterdata/po_detail.html', context)


@login_required
def create_invoice(request, pk):
	# udpate qty ready and qty to be shipped
	po_products = ProductPo.objects.filter(po_order=pk)

	qty_in_ready = 0
	qty_in_invoice = 0
	qty_in_shipped = 0
	new_qty_ready = 0
	new_qty_shipped = 0
	po_customer = ''
	po_code = ''

	check_record = Invoice.objects.all()
	invoice_no = 0
	if check_record.exists():
		check_record = Invoice.objects.latest('id')
		invoice_no = int(check_record.invoice_no) + 1
	else:
		invoice_no = 101

	for product in po_products:
		qty_in_ready = product.qty_ready
		qty_in_invoice = product.qty_invoice
		qty_in_shipped = product.qty_shipped
		new_qty_ready = product.qty_ready - product.qty_invoice
		new_qty_shipped = qty_in_shipped + product.qty_invoice

		query = ProductPo.objects.get(pk=product.id)
		query.qty_ready = new_qty_ready
		query.qty_invoice = 0
		query.qty_shipped = new_qty_shipped
		query.save()

		po_customer = PoOrder(id=product.po_order.id)
		po_code = Product(id=product.code.id)

		if qty_in_invoice != 0:
			query_insert = Invoice(
				invoice_no=invoice_no,
				po_customer=po_customer,
				code = po_code,
				send_to_be_shipped = qty_in_invoice
			)
			query_insert.save()

	return HttpResponseRedirect('/masterdata/display-invoice/{}'.format(invoice_no))


@login_required
def display_invoice(request, pk):
	invoice = Invoice.objects.filter(invoice_no=pk).order_by('-id')

	total_price = 0
	total_qty = 0
	created_at = ''
	invoice_no = ''
	po_customer = ''

	for item in invoice:
		total_qty += item.send_to_be_shipped
		total_price += (item.code.pub_price * item.send_to_be_shipped)
		created_at = item.created_at
		invoice_no = item.invoice_no
		po_customer = item.po_customer

	cust_details = PoOrder.objects.get(po_customer=po_customer)
	name = cust_details.customer.name
	address = cust_details.customer.address
	phone = cust_details.customer.phone
	email = cust_details.customer.email

	context = {
		'page_title': 'Invoices',
		'invoice': invoice,
		'total_qty': total_qty,
		'total_price': total_price,
		'created_at': created_at,
		'invoice_no': invoice_no,
		'po_customer': po_customer,
		'name': name,
		'address': address,
		'phone': phone,
		'email': email,
	}

	return render(request, 'masterdata/display_invoice.html', context)


@login_required
def all_invoices(request):
	all_invoices = Invoice.objects.all().values('invoice_no', 'po_customer').order_by('-invoice_no').distinct()

	context = {
		'page_title': 'Invoices',
		'all_invoices': all_invoices,
	}

	return render(request, 'masterdata/all_invoices.html', context)	


@login_required
def yearly_report(request):	
	years_form = YearsForm()

	context = {
		'page_title': 'Reports',
		'years_form': years_form,
	}

	if request.method == 'POST':
		years_form = YearsForm(request.POST)

		if years_form.is_valid():
			context['year'] = request.POST['year']
			year = context['year']

			po_order = PoOrder.objects.filter(ready_date__year=year)

			print(year)

			context['po_order'] = po_order

			return render(request, 'masterdata/yearly_report.html', context)

		else:
			years_form = YearsForm()

	return render(request, 'masterdata/yearly_report.html', context)

outsource/masterdata/templates/masterdata/all_invoices.html
{% extends "layout.html" %}

{% load masterdata_extras %}
{% load humanize %}

{% block title %}
	{{ page_title }}
{% endblock title %}

{% block content %}
	<h1>{{ page_title }}</h1>

	<div class="table-responsive-md">
		<table class="table table-striped">
			<thead class="thead-dark">
				<tr>
					<th scope="col">#</th>
					<th scope="col">Invoice #</th>
					<th scope="col">PO #</th>
					<th scope="col">Customer</th>
					<th scope="col">Total Qty</th>
					<th scope="col">Total Amount</th>
					<th scope="col">Invoice Created</th>
				</tr>
			</thead>
			<tbody>
			{% for invoice in all_invoices  %}
				<tr>
					<th scope="row">{{ forloop.counter }}</th>
					<td><a href="{% url 'masterdata:display_invoice' pk=invoice.invoice_no %}" target="_blank">{{ invoice.invoice_no }}</a></td>
					<td>{{ invoice.po_customer|get_po }}</td>
					<td>{{ invoice.invoice_no|get_cust_name }}</td>
					<td>{{ invoice.invoice_no|get_total_qty|intcomma }}</td>
					<td>Rp. {{ invoice.invoice_no|get_total_amount|intcomma }}</td>
					<td>{{ invoice.invoice_no|get_inv_date|date:"d/M/Y" }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock content %}

outsource/masterdata/templates/masterdata/display_invoice.html
{% load masterdata_extras %}
{% load humanize %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

	<title>Invoice: {{ invoice_no }}</title>
</head>
<body>
	<div class="container">
		<p>
			<h1>Hexa Bali</h1>
			<h5>
				Jl. Pantai Berawa No. 12<br>
				Canggu, Kuta-Bali 80361<br>
				0361-836454
			</h5>
		</p>
		<h4>Invoice: {{ invoice_no }}</h4>
		<p>
			PO #: {{ po_customer }}<br>
			Customer Name: {{ name }}<br>
			Address: {{ address }}<br>
			Phone: {{ phone }}<br>
			Email: {{ email|urlize }}<br>
			Date: {{ created_at|date:"d/M/Y" }}
		</p>
		<table class="table table-striped">
		<thead class="thead-dark">
			<tr>
				<th scope="col">#</th>
				<th scope="col">Product Code</th>
				<th scope="col">Qty</th>
				<th scope="col">Published Price</th>
				<th scope="col">Total Amount</th>
			</tr>
		</thead>
		<tbody>
		{% for item in invoice  %}
			<tr>
				<th scope="row">{{ forloop.counter }}</th>
				<td>{{ item.code.code }}</td>
				<td>{{ item.send_to_be_shipped|intcomma }}</td>
				<td>Rp. {{ item.code.pub_price|intcomma }}</td>
				<td>Rp. {{ item.code.pub_price|multiply:item.send_to_be_shipped|intcomma }}</td>
			</tr>
		{% endfor %}
			<tr>
				<td></td>
				<td><strong>TOTAL</strong></td>
				<td><strong>{{ total_qty|intcomma }}</strong></td>
				<td></td>
				<td><strong>Rp. {{ total_price|intcomma }}</strong></td>
			</tr>
		</tbody>
	</table>
	<br>
	<p>
		<h5>Please transfer payment to:</h5><br>
		Bank: Bank Central Asia (BCA)<br>
		Acc #: 9862845344<br>
		Acc Name: CV Hexa Bali<br>
		Branch: Kuta, Bali<br>
	</p>
	<p>
		Send proof of transfer to <a href="mailto:accounts@hexaid.com">accounts@hexaid.com</a>
	</p>
	</div>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

outsource/masterdata/templates/masterdata/index.html
{% extends "layout.html" %}

{% block title %}
	{{ page_title }}
{% endblock title %}

{% block content %}
	<h1>{{ page_title }}</h1>
	<form method="POST">
		{% csrf_token %}
		<div class="form-group mt-5">
			<strong>{{check_form.po_customer.label_tag}}</strong>
			{{check_form.po_customer}}
		</div>
		<button type="submit" class="btn btn-primary btn-lg active mt-3 mx-auto">Check PO</button>
	</form>
{% endblock content %}

outsource/masterdata/templates/masterdata/po_detail.html
{% extends "layout.html" %}

{% load masterdata_extras %}
{% load humanize %}

{% block title %}
	{{ page_title }}
{% endblock title %}

{% block content %}
	<h2>{{ po_numbers }}</h2>
	<h5>Customer: {{ po_customer }}</h5>
	<h5>Ready: {{ ready_date|date:"d/M/Y" }}</h5>
	<h5>Shipment: {{ shipment_date|date:"d/M/Y" }}</h5>
	<h5>PO Supplier: {{ po_supplier }}</h5>
	{% if po_status == 'completed' %}
	<p>
		<button type="button" class="btn btn-success" disabled>{{ po_status|upper }}</button>
	</p>
	{% else %}
		
		{% if user.is_authenticated %}
			<p align="left">
			<!-- Button trigger modal -->
			<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#exampleModalCenter" {% if total_qty_invoice == 0 %}disabled {% else %} {% endif %} >
			  Invoice this PO
			</button>

			<!-- Modal -->
			<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
			  <div class="modal-dialog modal-dialog-centered" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <h5 class="modal-title" id="exampleModalLongTitle">Confirmation</h5>
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			          <span aria-hidden="true">&times;</span>
			        </button>
			      </div>
			      <div class="modal-body">
			        Are you sure you want to invoice this PO?
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
			        <a href="{% url 'masterdata:invoice' pk=prod_id %}"><button type="button" class="btn btn-primary">Yes I am sure</button></a>
			      </div>
			    </div>
			  </div>
			</div>
			</p>
		{% else %}
			<p>
				<button type="button" class="btn btn-warning" disabled>{{ po_status|upper }}</button>
			</p>
		{%endif %}

	{% endif %}

	<div class="table-responsive-md">
		<table class="table table-striped">
			<thead class="thead-dark">
				<tr>
					<th scope="col">#</th>
					<th scope="col">Product Code</th>
					<th scope="col">Qty Order</th>
					<th scope="col">Qty Ready</th>
					<th scope="col">Qty invoice</th>
					<th scope="col">Qty Shipped</th>
					<th scope="col">Qty Balance</th>
					<th scope="col">Published Price</th>
					<th scope="col">Amount Order</th>
					<th scope="col">Amount Ready</th>
					<th scope="col">Amount Invoice</th>
					<th scope="col">Amount Shipped</th>
					
					{% if user.is_authenticated %}
						<th scope="col">Amount Profit</th>
					{% else %}

					{% endif%}
					<th scope="col">Print Barcode</th>
					<th scope="col">Product Image</th>
				</tr>
			</thead>
			<tbody>
			{% for product in po_products  %}
				<tr>
					<th scope="row">{{ forloop.counter }}</th>
					<td>{{ product.code.code }}</td>
					<td>{{ product.qty_order|intcomma }}</td>
					<td>{{ product.qty_ready|intcomma }}</td>
					<td>{{ product.qty_invoice|intcomma }}</td>
					<td>{{ product.qty_shipped|intcomma }}</td>
					<td>{{ product.qty_shipped|subtract:product.qty_order|intcomma }}</td>
					<td>{{ product.code.pub_price|intcomma }}</td>
					<td>{{ product.code.pub_price|multiply:product.qty_order|intcomma }}</td>
					<td>{{ product.code.pub_price|multiply:product.qty_ready|intcomma }}</td>
					<td>{{ product.code.pub_price|multiply:product.qty_invoice|intcomma }}</td>
					<td>{{ product.code.pub_price|multiply:product.qty_shipped|intcomma }}</td>

					{% if user.is_authenticated %}
						<td>{{ product.code.prod_price|multiply:product.qty_shipped|intcomma }}</td>
					{% else %}

					{% endif%}
					<td><a href="{% url 'masterdata:barcode' pk=product.code.id %}" target="_blank">[create]</a></td>
					<td>
						<a href="{{ product.code.image.url }}" target="_blank">
							<img class="rounded-circle" src="{{ product.code.image.url }}" width="50px">
						</a>
					</td> 
				</tr>
			{% endfor %}
				<tr>
					<td></td>
					<td><strong>TOTAL</strong></td>
					<td><strong>{{ total_qty_order|intcomma }}</strong></td>
					<td><strong>{{ total_qty_ready|intcomma }}</strong></td>
					<td><strong>{{ total_qty_invoice|intcomma }}</strong></td>
					<td><strong>{{ total_qty_shipped|intcomma }}</strong></td>
					<td><strong>{{ total_qty_shipped|subtract:total_qty_order|intcomma }}</strong></td>
					<td></td>
					<td><strong>{{ total_amount_order|intcomma }}</strong></td>
					<td><strong>{{ total_amount_ready|intcomma }}</strong></td>
					<td><strong>{{ total_amount_invoice|intcomma }}</strong></td>
					<td><strong>{{ total_amount_shipped|intcomma }}</strong></td>

					{% if user.is_authenticated %}
						<td><strong>{{ total_amount_profit|intcomma }}</strong></td>
						<td></td>
					{% else %}

					{% endif%}
					
					<td></td>
				</tr>
			</tbody>
		</table>
	</div>
{% endblock content %}

outsource/masterdata/templates/masterdata/po_list.html
{% extends "layout.html" %}

{% load masterdata_extras %}
{% load humanize %}

{% block title %}
	{{ page_title }}
{% endblock title %}

{% block content %}
	<h1>{{ page_title }}</h1>

  <div class="table-responsive-md">
  	<table class="table table-sm table-bordered">
  			<thead class="thead-dark">
  			<tr>
    				<th scope="col">#</th>
    				<th scope="col">PO Numbers</th>
    				<th scope="col">Customer</th>
    				<th scope="col">PO Supplier</th>
            <th scope="col">Total Qty Order</th>
            <th scope="col">Total Amount Order</th>
    				<th scope="col">Ready Date</th>
    				<th scope="col">Shipment Date</th>
    				<th scope="col">Status</th>
  			</tr>
  			</thead>
  			<tbody>
  			
  			{% for po in po_list %}
  			<tr {% if po.status == 'open' %}class="table-warning"{% else %}class="table-success"{% endif %}>
    				<th scope="row">{{ forloop.counter }}</th>
    					<td>
    						<a href="{% url 'masterdata:detail' pk=po.pk %}">
    							{{ po.po_customer }}
    						</a>
    					</td>
    					<td>{{ po.customer.name }}</td>
    					<td>{{ po.po_supplier }}</td>
              <td>{{ po.id|get_total_qty_detail|intcomma }}</td>
              <td>Rp. {{ po.id|get_total_amount_detail|intcomma }}</td>
    					<td>{{ po.ready_date|date:"d/M/Y" }}</td>
    					<td>{{ po.shipment_date|date:"d/M/Y" }}</td>
    					<td>{{ po.status|upper }}</td>
  			</tr>
  			{% endfor %}

  			</tbody>
  	</table>
  </div>
{% endblock content %}

outsource/masterdata/templates/masterdata/po_status.html
{% extends "layout.html" %}

{% load masterdata_extras %}
{% load humanize %}

{% block title %}
	{{ page_title }}
{% endblock title %}

{% block content %}
	<h1>{{ po_customer }}</h1>

  <div class="table-responsive-md">
  	<table class="table table-bordered">
  			<thead class="thead-dark">
  			<tr>
    				<th scope="col">#</th>
    				<th scope="col">PO Numbers</th>
    				<th scope="col">Customer</th>
    				<th scope="col">PO Supplier</th>
            <th scope="col">Total Qty Order</th>
            <th scope="col">Total Amount Order</th>
    				<th scope="col">Ready Date</th>
    				<th scope="col">Shipment Date</th>
    				<th scope="col">Status</th>
  			</tr>
  			</thead>
  			<tbody>
  			
  			<tr {% if po_status == 'open' %}class="table-warning"{% else %}class="table-success"{% endif %}>
    				<th scope="row">1</th>
    					<td>
    						<a href="{% url 'masterdata:detail' pk=po_id %}">
    							{{ po_customer }}
    						</a>
    					</td>
    					<td>{{ po_name }}</td>
    					<td>{{ po_supplier }}</td>
              <td>{{ po_id|get_total_qty_detail|intcomma }}</td>
              <td>Rp. {{ po_id|get_total_amount_detail|intcomma }}</td>
    					<td>{{ po_ready|date:"d/M/Y" }}</td>
    					<td>{{ po_shipment|date:"d/M/Y" }}</td>
    					<td>{{ po_status|upper }}</td>
  			</tr>

  			</tbody>
  	</table>
  </div>
{% endblock content %}