outsource/masterdata/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^polist/', views.po_list, name='polist'),
	url(r'^all-invoices/', views.all_invoices, name='all_invoices'),
	url(r'^yearly-report/', views.yearly_report, name='yearly_report'),
	url(r'^detail/(?P<pk>\d+)$', views.po_detail, name='detail'),
	url(r'^barcode/(?P<pk>\d+)$', views.barcode, name='barcode'),
	url(r'^invoice/(?P<pk>\d+)$', views.create_invoice, name='invoice'),
	url(r'^display-invoice/(?P<pk>\d+)$', views.display_invoice, name='display_invoice'),
	url(r'^$', views.index, name='index'),
]

outsource/outsource/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^masterdata/', include('masterdata.urls', namespace='masterdata')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

outsource/templates/layout.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <title>
    	{% block title %}
			
		  {% endblock title %}
    </title>

  </head>
  <body>
    <div class="container">
    	<nav class="nav nav-pills nav-fill" style="padding:20px 0px 50px 0px;">
  	  	<a class="nav-item nav-link {% if page_title == 'PO Status' %}active{% endif %}" href="{% url 'masterdata:index' %}">PO Status</a>
        {% if user.is_authenticated %}
  	  	<a class="nav-item nav-link {% if page_title == 'PO List' or page_title == 'PO Detail' %}active{% endif %}" href="{% url 'masterdata:polist' %}">PO List</a>
        <a class="nav-item nav-link {% if page_title == 'Invoices' %}active{% endif %}" href="{% url 'masterdata:all_invoices' %}">Invoices</a>
        <a class="nav-item nav-link {% if page_title == 'Reports' %}active{% endif %}" href="{% url 'masterdata:yearly_report' %}">Reports</a>
        {% endif %}
  	   </nav>
  	{% block content %}
  		
  	{% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </div>
  </body>
</html>